# -*- coding: utf-8 -*-
"""Day_01_Introduction_to_Data_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AMM0hUj5pVr0h6mO_bIZ_-DtZQeooZJ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df=pd.read_csv('student_performance.csv')

df.head()

df.tail()

df.shape[0]

df.shape[0:6]

print(df.name.tolist())

df.dtypes

df.describe()

df.isnull().sum()

df = df[df['math_score'] != 5]

df = df.fillna(df.mean(numeric_only=True))

df=df.dropna()

display(df)

df=df[df['math_score']!=5]
display(df.head())

print(df['department'].value_counts())

print(df['gender'].value_counts())

print(df['city'].value_counts())

Mechanicalstd=df[df['department']=='Mechanical']
print(f"number Mechanical std: {len(Mechanicalstd)}")

print(df[df['programming_score']=='mumbai'])

chennai_students = df[df['city'] == 'Chennai']
display(chennai_students[['name', 'math_score', 'science_score', 'english_score', 'programming_score']])

city_students = df[(df['city'] == 'Chennai') | (df['city'] == 'Mumbai')]
display(city_students[['name', 'programming_score']])

city_students_and = df[(df['city'] == 'Chennai') & (df['city'] == 'Mumbai')]
display(city_students_and[['name', 'programming_score']])

high_att=df[df['attendance_percentage']<=75]
print(high_att)

display(df['attendance_percentage'])

df['tot']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
display(df['tot'])

least=df.loc[df['tot'].idxmin()]
print(least)