# -*- coding: utf-8 -*-
"""Day 1 Mini project-Student Data Explorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_OFOZ9oq_ridU4CQPOq7uLbWCtE59VH
"""

import pandas as pd

df = pd.read_csv("student_performance.csv")

df.head()

print(f"Total Number of Students : {df.shape[0]}")

print(f"Total Number of Columns  : {df.shape[1]}")

print(f"Unique Departments: {df['department'].nunique()}")

dept_count = df["department"].value_counts()

for dept, count in dept_count.items():
    print(f"{dept} : {count} students")

print(f"Highest Math Score : {df['math_score'].max()}")

print(f"Lowest Math Score: {df['math_score'].min()}")

print(f"Average Math Score : {df['math_score'].mean():.2f}")

print(f"Average Programming Score : {df['programming_score'].mean():.2f}")

print(f"Average Attendance: {df['attendance_percentage'].mean():.2f}")

df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
gender_avg = df.groupby("gender")["total_score"].mean()

for gender, avg in gender_avg.items():
    print(f"{gender} Average Total Score : {avg:.2f}")

top_students = df.sort_values(by="total_score", ascending=False).head(5)

for index, row in top_students.iterrows():
    print(f"Name : {row['name']}")
    print(f"Department : {row['department']}")
    print(f"Total Score : {row['total_score']}")

low_attendance = df[df["attendance_percentage"] < 75]

if not low_attendance.empty:
    for index, row in low_attendance.iterrows():
        print(f"Name : {row['name']}")
        print(f"Department : {row['department']}")
        print(f"Attendance : {row['attendance_percentage']}%")
else:
    print("All students have attendance above 75%")

electronics_students = df[df["department"] == "ECE"].shape[0]
print(f"1. Students from Electronics Department : {electronics_students}")

female_attendance = df[df["gender"] == "Female"]["attendance_percentage"].mean()
print(f"2. Average Attendance of Female Students : {female_attendance:.2f}")

lowest_prog_student = df.loc[df["programming_score"].idxmin()]
print(f"3. Student with Lowest Programming Score : {lowest_prog_student['name']}")

above_80_math = df[df["math_score"] > 80].shape[0]
print(f"4. Students Scored Above 80 in Math : {above_80_math}")

avg_total_above_90 = df[df["attendance_percentage"] > 90]["total_score"].mean()
print(f"5. Average Total Score (Attendance > 90%) : {avg_total_above_90:.2f}")